- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: kubeadm init --pod-network-cidr=10.217.0.0/16
  register: init_cluster
